### PR TITLE
Allow detection of MPI_Abort condition in library call

### PR DESCRIPTION
**Pull request by rbberger**
The return value of `lammps_get_last_error_message` now encodes if the last
error was recoverable or should cause an `MPI_Abort`. The driving code is
responsible of reacting to the error and calling `MPI_Abort` on the
communicator it passed to the LAMMPS instance.

### CODE REVIEW

**Review by akohlmey — CHANGES_REQUESTED** [review]
It seems to me, that the code in lammps.py and library.cpp assumes, that the shared library was compiled with -DLAMMPS_EXCEPTIONS. This should not be. For as long as we have the define, it should be applied consistently across the library (static or shared) and executables.

**Comment by rbberger** [comment]
@akohlmey please review again. I've made `LAMMPS_EXCEPTIONS` code paths optional and also the Python wrapper makes sure the library functions exist. Calling `MPI_Abort` is responsibility of the calling code. The wrapper will simply raise an `MPIAbortException`.

**Comment by rbberger** [comment]
@akohlmey please have a look at how I've used the macro approach to ensure all exceptions are caught in the library interface. There is like two special cases which can occur during construction of the LAMMPS objects. At that point in time the `Error` class instance doesn't exist yet, so I'm capturing exceptions directly. In all other cases I'm using the macros and storing the error on a per-instance basis.

**Review by akohlmey — APPROVED** [review]

**Comment by akohlmey** [comment]
@rbberger this seems to be working as expected. no more python crashes with -DLAMMPS_EXCEPTIONS, clean termination without. I'll hand it over to @sjplimp now and we'll have to see how it does, after it is released. i suggest you post to lammps-users notifying people using the python wrapper of the improvements and benefits.

**Pull request merged**
